### ISSUE TITLE
A question about PEViD-UHD dateset

### ISSUE THREAD

**Issue by wyg1997** [previtus/intership_project#1]
Thanks for your research!

I want to use PEViD-UHD dataset to run a object detection with 4k~8k images.
But the video I downloaded from ftp server at "tremplin.epfl.ch/PEViD-UHD/Original_UHD_MP4/" is 30 fps and about 1060 frames in all.
Strangely, the annotation files ( e.g. Exchanging_bags_day_indoor_1_4K.xgtf ) just have 390 frames in all. And the number of frames are different.

Have I downloaded the wrong files?

I really appreciate if you could tell me how to do.

There are two images showing the different informations.
![image](https://user-images.githubusercontent.com/39889784/62820289-c8cddf80-bb94-11e9-8a30-10b9769c69ce.png)
![image](https://user-images.githubusercontent.com/39889784/62820298-dbe0af80-bb94-11e9-9b82-57efe20ec64e.png)

**Comment by previtus** [comment]
Hello wyg1997,
I came across similar difficulties when dealing with the PEViD-UHD dataset. The original videos are longer than the annotated segments and if I am not mistaken, there was no easy way how to find where they start.

I **extracted frames at 30 fps and then found where each segment starts** (manually checking every sequence).

You can try if this works for you as well on one example video "Exchanging_bags_day_indoor_2_original.mp4":

- Convert video to frames at 30 fps:
`ffmpeg -i Exchanging_bags_day_indoor_2_original.mp4 -vf fps=30 frame_%d.jpg
`

- For this video I found the annotation to fit the range of frames:
`frame_186.jpg to frame_541.jpg
`

- (Optional) I was working with annotation converted into the format used by [LabelImg](https://github.com/tzutalin/labelImg) from the .xgtf format (in this case it would be _Exchanging_bags_day_indoor_2_4K.xgtf_) which can be also used to manually check the results. The conversion was done using: [_side_projects/annotation_conversion/convert_pevid_to_bboxes.py](https://github.com/previtus/AttentionPipeline/blob/master/_side_projects/annotation_conversion/convert_pevid_to_bboxes.py)
If you want to use it, prepare the extracted folder by keeping only files frame_186.jpg to frame_541.jpg and then change paths:
input_gt_file = "Exchanging_bags_day_indoor_2_4K.xgtf" (downloaded from the website)
output_folder = "Exchanging_bags_day_indoor_2_original_frames/" (where you extracted frames using ffmpeg)

If this works for you, I can dig around my hard drives and find the ranges for other videos I worked with: 
- Exchanging_bags_day_indoor_2
- Exchanging_bags_day_indoor_3
- Exchanging_bags_day_outdoor_4
- Exchanging_bags_day_outdoor_5
- Stealing_day_indoor_2
- Stealing_day_indoor_3
- Stealing_day_indoor_4
- Stealing_day_outdoor_5
- Stealing_day_outdoor_8
- Stealing_day_outdoor_9

I remember this being a bit painful at the start, but when I processed them I was only working with my exported files and didn't need to worry about the original files.

Hope this helps :),
~ Vitek

**Comment by previtus** [comment]
![labelImg_screen](https://user-images.githubusercontent.com/1137990/63172564-4e8ed680-c03e-11e9-8033-2d1d884da5ac.png)
^^ This is what you end up eventually getting... (labelImg is quite good to sanity-check the data)

**Comment by previtus** [comment]
Using this command:
`ffmpeg -i <video file name>.mp4 -vf fps=30 %04d.jpg`

| Video file  | Corresponding frames |
| ------------- | ------------- |
| Exchanging_bags_day_indoor_2  | 0186.jpg - 0541.jpg  |
| Exchanging_bags_day_indoor_3  | 0125.jpg - 0416.jpg  |
| Exchanging_bags_day_outdoor_4  | 0061.jpg - 0325.jpg  |
| Exchanging_bags_day_outdoor_5  | 0100.jpg - 0419.jpg  |
| Stealing_day_indoor_2  | 0157.jpg - 0366.jpg |
| Stealing_day_indoor_3  | 0213.jpg - 0597.jpg |
| Stealing_day_indoor_4  | 0364.jpg - 0600.jpg |
| Stealing_day_outdoor_5  | 0117.jpg - 0482.jpg  |
| Stealing_day_outdoor_8  | 0090.jpg - 0419.jpg  |
| Stealing_day_outdoor_9  | 0140.jpg - 0370.jpg  |

**Comment by wyg1997** [comment]
Thanks for your help. It is very helpful for me to get the right images dataset.
