### ISSUE TITLE
From where can i download PEViD-UHD

### ISSUE THREAD

**Issue by ghost** [previtus/intership_project#2]
I couldn't find any links for download and appreciate it if you can help me with it.

**Comment by previtus** [comment]
Dear Tamir,
There were three sources for the used datasets - the **publically available PEViD-UHD**, our **own recorded dataset** (which is sadly not public and had to be manually annotated) and finally the **video accessible on YouTube** at https://www.youtube.com/watch?v=gdnHLE_HCX0 (this one was again used without annotation, simply to measure the speed of our code on 8K footage).

**PEViD-UHD**

- Perhaps this dataset would be the best to start with, as it contains annotation. More details about how to use it (sadly it's not entirely straightforward and it required some work in making sense of the frame to annotation correspondence) can be found here: https://github.com/previtus/AttentionPipeline/issues/1

**publically available 8k video: https://www.youtube.com/watch?v=gdnHLE_HCX0**

- In this case, I would recommend downloading the video, sampling some frames from it (for example by using ffmpeg) and then running our code to test the speed.

- You can probably use something like: `ffmpeg -i video.webm -vf fps=5 frame_%d.jpg`


Hope this helps,
Vit Ruzicka
