### ISSUE TITLE
Regarding Dataset

### ISSUE THREAD

**Issue by mahendra-gehlot** [previtus/intership_project#4]
Hey, I am trying to fetch PeVID-UHD datasets. The server is not responding. Do you have a mirror of the dataset ? or Can you help me get the dataset?

Furthermore, Can you show how you arranged your codes and dataset while implementing (directory snip) when you worked on this project?

I am also facing problems with implementation with the newer versions of libraries. Can you share points to keep in mind during implementation in latest versions of libraries?

**Comment by previtus** [comment]
Dear Mahendra, apologies for the slow response, things have been busy on my side :)
It seems like the server which had the PEViD-UHD dataset is indeed down. To partially answer your question, I was able to find the mp4 files and the ground truth labels (in xgtf format) on my hard drive and I can re-upload them as a mirror. 

Importantly, note that this data is still under the copyright from the website https://www.epfl.ch/labs/mmspg/downloads/pevid-uhd/ - however given this following section, I think it is alright to re-upload the mirror for research purposes:
> **Permission is hereby granted**, without written agreement and without license or royalty fees, to use, **copy**, modify, and distribute the data provided and its documentation **for research purpose only.**

PEViD-UHD dataset mirror: https://drive.google.com/drive/folders/1w0lOWJCp3nG_I48zj7m077OJPi1quaXI?usp=sharing
This contains only the contents of the "Original_UHD_MP4" folder (~3.3GB).

Please follow the description in https://github.com/previtus/AttentionPipeline/issues/1 to save only the relevant and annotated frames from the video (into jpgs and then ideally individual xml files).

**Comment by mahendra-gehlot** [comment]
Thank You!
